name: story_book
description: "An interactive Story Book"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^0.20.1
  path_provider: ^2.0.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/audio/story_1/
  - assets/audio/story_2/
  - assets/audio/story_3/
  - assets/images/story_1/
  - assets/images/story_2/
  - assets/images/story_3/
  - assets/story/
  - assets/images/
